---
title: "MGS_Occupancy"
author: "Annie Kellner"
date: "2025-04-30"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r libraries}

library(tidyverse)
library(unmarked)
library(kableExtra)
library(terra)

```


### Tabulating data


```{r load-data}

detNA <- readRDS("./Data/detection_withNAs.Rds") # detections with NA's subbed for non-operational camera days
cams <- readRDS("./Data/camera_operation.Rds")

# Tabulate 0's, 1's, NA's

tabData <- detNA %>%
  select(-1) %>%
  pivot_longer(everything()) %>%
  count(value) %>%
  arrange(value) 

kableExtra::kbl(tabData) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                            position = "center") %>%
  kableExtra::row_spec(0, bold = TRUE)  # Makes header row bold

```


```{r}

tabCams <- cams %>%
  select(-1) %>%
  pivot_longer(everything()) %>%
  count(value) %>%
  arrange(value) 

kableExtra::kbl(tabCams) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                            position = "center") %>%
  kableExtra::row_spec(0, bold = TRUE)  # Makes header row bold

```


# Modeling

## Model 1
  - All Animals
  - All Cameras
  - Detection Trend
  - Random Effect of Individual Camera

```{r}

#umf <- readRDS('./Data/umf_05152025.Rds')

# Model 
  # quadratic term on ordinal date (for parabolic detection prob)
  # random effect for individual camera

mgs.occu <- occu(~ scOrdinal + scOrdinal2 ~ (1|site),
                 data = umf,
                 linkPsi = "logit")

pred_scaled <- predict(mgs.occu, type = "state")



cat("Range:", range(pred_scaled$Predicted))
cat("Mean:", mean(pred_scaled$Predicted))

```

## Model 2: same as 1 but *without* detection trend


```{r}

mgs.occu.noDet <- occu(~ 1 ~ 1 + (1|site),
                       data = umf,
                       linkPsi = "logit")

noDet_pred <- predict(mgs.occu.noDet, type = "state")

noDet_pred

```

This model is too simplistic because it does not account for any spatiotemporal variation. It cannot distinguish between absence and non-detection, so the 95% CI is (0,1).



